name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: '0 0 * * *'}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ['master', 'main']}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          config_timezone: America/Toronto
          token: ${{ secrets.METRICS_TOKEN }}